Server/src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="L'email est déja utilisé!")
 */
class User implements UserInterface
{

     /**
     * @var array
     * @ORM\Column(type="array")
     */
    private $roles;
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $fixed_delivery_price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password; 
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getFixedDeliveryPrice(): ?bool
    {
        return $this->fixed_delivery_price;
    }

    public function setFixedDeliveryPrice(?bool $fixed_delivery_price): self
    {
        $this->fixed_delivery_price = $fixed_delivery_price;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /*
    * @return array (role|string)[] the user roles
    */
    public function getRoles()
    {
        return $this->roles; 
        
    }
 
    public function setRoles(array $roles)
    {
        $this->roles = $roles;
        return $this;
    }

    public function getUsername(){

    }

    public function eraseCredentials(){}
    public function getSalt(){
        return null;
    }
}

Server/src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
           
            ->add('name')
            ->add('firstname')
            ->add('email')
            ->add('adress')
            ->add('telephone')
            ->add('fixed_delivery_price')
            ->add('password',PasswordType::class)
             ->add('roles', ChoiceType::class,
                array(
                    'multiple'=> true,
                    'choices'=>[
                        'Administrateur' => 'ROLE_ADMIN',
                        'Utilisateur' => 'ROLE_USER'
                    ]
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

Server/src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use FOS\RestBundle\View\View;
use App\Repository\UserRepository;
use Symfony\Component\Validator\Validation;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Type;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use FOS\RestBundle\Controller\Annotations as FOSRest;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    /**
     * @FOSRest\Get("api/admin/users")
     * 
     */
    public function allUsers()
    {
        $repository = $this->getDoctrine()->getRepository(User::class);
        $users =  $repository->findAll();

        return View::create($users, Response::HTTP_OK , []);
      
    }

    /**
     * @FOSRest\Post("api/admin/users/new")
     */
    public function new(Request $request, UserPasswordEncoderInterface $encoder)
    {
        $user = new User();

        $content = json_decode(
            $request->getContent(),true
        );

        $validator = Validation::createValidator();

        $constraint = new Assert\Collection(array(
            // the keys correspond to the keys in the input array
            'password' => new Assert\Length(array('min' => 3, 'minMessage'=>'Votre mot de passe doit contenir minimum 3 caracteres')),
            'email' => new Assert\Email(array('message'=> 'Votre email est incorrect')),
            'firstname' => new Assert\Length(array('min' => 2, 'minMessage'=>'Votre prenom doit contenir minimum 2 caracteres')),
            'name' => new Assert\Length(array('min' => 2, 'minMessage'=>'Votre nom doit contenir minimum 2 caracteres')),
            'adress'=> new Assert\Length(array('min' => 2, 'minMessage'=>'Votre adresse ne contient que 2 caractère')),
            'telephone'=> new Assert\Length(array('min' => 2, 'minMessage'=>'Votre adresse ne contient que 2 caractère')),
        ));

        $violations = $validator->validate($content, $constraint);

        if ($violations->count() > 0) {
            return View::create(["error" => (string)$violations], Response::HTTP_CONFLICT , []);
        }

        $email = $content['email'];
        $name = $content['name'];
        $firstname = $content['firstname'];
        $adress= $content['adress'];
        $telephone =$content['telephone'];
        $password = $content['password'];

        $user->setPassword($encoder->encodePassword($user, $password));
        $user->setEmail($email);
        $user->setName($name);
        $user->setFirstname($firstname);
        $user->setFixedDeliveryPrice(false);
        $user->setAdress($adress);
        $user->setTelephone($telephone);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($user);
        $entityManager->flush();

        return View::create(["success" => $user->getEmail(). " est bien enregistré"], Response::HTTP_OK , []);

    }

    /**
     * @FOSRest\Get("api/admin/users/{id}")
     */
    public function show(User $user)
    {
        return View::create($user, Response::HTTP_OK , []);
    }

    /**
     * @FOSRest\Put("api/admin/users/{id}/edit")
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $encoder)
    {
        $content = json_decode(
           $request->getContent(),true
        );

        $validator = Validation::createValidator();

        $constraint = new Assert\Collection(array(
            // the keys correspond to the keys in the input array
            'password' => new Assert\Length(array('min' => 3, 'minMessage'=>'Votre mot de passe doit contenir minimum 3 caracteres')),
            'email' => new Assert\Email(array('message'=> 'Votre email est incorrect')),
            'firstname' => new Assert\Length(array('min' => 2, 'minMessage'=>'Votre prenom doit contenir minimum 2 caracteres')),
            'name' => new Assert\Length(array('min' => 2, 'minMessage'=>'Votre nom doit contenir minimum 2 caracteres')),
            'adress'=> new Assert\Length(array('min' => 2, 'minMessage'=>'fgffffd')),
            'telephone'=> new Assert\Length(array('min' => 2, 'minMessage'=>'fgffffd')),
        ));

        $violations = $validator->validate($content, $constraint);

        if ($violations->count() > 0) {
            return View::create(["error" => (string)$violations], Response::HTTP_CONFLICT , []);
        }

        $email = $content['email'];
        $name = $content['name'];
        $firstname = $content['firstname'];
        $adress= $content['adress'];
        $telephone =$content['telephone'];
        $password = $content['password'];

        $user->setPassword($encoder->encodePassword($user, $password));
        $user->setEmail($email);
        $user->setName($name);
        $user->setFirstname($firstname);
        $user->setFixedDeliveryPrice(false);
        $user->setAdress($adress);
        $user->setTelephone($telephone);
        $manager = $this->getDoctrine()->getManager();
        $manager->persist($user);
        $manager->flush();

        return View::create(["success" => $user->getEmail(). " profil modifier"], Response::HTTP_OK , []);
    }
    
    /**
     * @FOSRest\Delete("api/admin/users/{id}")
     */
    public function delete(Request $request, User $user)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($user);
        $entityManager->flush();

        return View::create(["success" => $user->getEmail(). " est supprimé"], Response::HTTP_OK , []);
    }
}

Server/templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

Server/templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Server/templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

Server/templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Firstname</th>
                <th>Email</th>
                <th>Adress</th>
                <th>Telephone</th>
                <th>Fixed_delivery_price</th>
                <th>Password</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.adress }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.fixedDeliveryPrice ? 'Yes' : 'No' }}</td>
                <td>{{ user.password }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

Server/templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

Server/templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.name }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ user.adress }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
            <tr>
                <th>Fixed_delivery_price</th>
                <td>{{ user.fixedDeliveryPrice ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}